### PR TITLE
feat(ses): Export SES Transforms

### PR DESCRIPTION
**Pull request by kumavis**
these transforms are useful, but are not exposed in the published package

### CODE REVIEW

**Review by erights — APPROVED** [review]
LGTM. Thanks!

**Comment by kriskowal** [comment]
Cool, will add to the NEWS.

**Comment by kriskowal** [comment]
@kumavis @erights, the current user interface for these methods is on the `Compartment.prototype.evaluate` method:

```js
   * @param {boolean} [options.__evadeHtmlCommentTest__]
   * @param {boolean} [options.__evadeImportExpressionTest__]
   * @param {boolean} [options.__rejectSomeDirectEvalExpressions__]
```

Is that satisfactory, and should I revert this if so? Exporting modules from the shim is an odd usage pattern and puts a bit of a burden on build time.

If we keep this change, we need to factor `transforms.js` out of `src/transforms.js` and only export these three public transform functions (not the internal ones used for censorship). On closer inspection, these changes are not yet releasable.

**Comment by erights** [comment]
My mistake. See https://github.com/endojs/endo/issues/609#issuecomment-797840103

**Pull request merged**
