### PR TITLE
WIP more types fixed

### PR DESCRIPTION
**Pull request by erights**
Does not yet type check.

Would reduce the #161 problem yet farther

### CODE REVIEW

**Comment by erights** [comment]
That's frightening. CI shows "All checks have passed" but I know `yarn lint:types` does not yet pass. Is it not being checked under CI?

**Comment by dckc** [comment]
@erights writes:
> ... Is it not being checked under CI?

sure looks like it is... I see `tsc --build jsconfig.json` in `packages/ses`:

https://github.com/Agoric/SES-shim/pull/566/checks?check_run_id=1755768983#step:9:44

**Comment by erights** [comment]
That's very weird. I see that now too. But I was seeing the other thing. Should have taken a screenshot ;)

**Review by dckc — CHANGES_REQUESTED** [review]
@erights , @kriskowal I suspect this is overtaken by events. If so, please close it.

If not, hit the "re-review" thingy to put it back on my queue, please.

**Comment by erights** [comment]
> @erights , @kriskowal I suspect this is overtaken by events. If so, please close it.

Seem right to me. Closing.

**Pull request closed without merging**
