### PR TITLE
WIP Rename the fatal form of assert to `vat.assert`

### PR DESCRIPTION
**Pull request by erights**

### CODE REVIEW

**Comment by erights** [comment]
Ready for review

**Review by kriskowal — APPROVED** [review]
Looks good.

My only worry here is that it seems very likely that “worker” will win any sufficiently inclusive naming contest against “vat”. It seems likely to me that “vat” will be a specialization of “worker”, and that “worker” methods will be sufficiently general for both environments.

**Comment by erights** [comment]
> My only worry here is that it seems very likely that “worker” will win any sufficiently inclusive naming contest against “vat”. It seems likely to me that “vat” will be a specialization of “worker”, and that “worker” methods will be sufficiently general for both environments.

Perhaps, but it would require a change from the current meaning of "worker". Right now, in the browser, the main thread is not considered a "worker". I think this is the case for the Node main thread as well.

**Comment by kriskowal** [comment]
It would seem an equal stretch of the imagination that there’s an initial realm or initial compartment as an initial worker.

**Comment by erights** [comment]
> It would seem an equal stretch of the imagination that there’s an initial realm or initial compartment as an initial worker.

I agree. But I'm not holding my breath waiting for browsers to change how they use existing browser terminology ;)

**Comment by kriskowal** [comment]
I suspect that this API is useful in environments that you would not call vats, and that you would not want to give it a different name in environments that were and were not vats. I am certain browser vendors would prefer to call it a worker, even in the main thread, than to adopt the new term “vat”. I suspect you would be nonplussed if “vat” came to refer the the execution environment of a browser main thread.

**Pull request merged**
