### PR TITLE
fix(ses): Bad RegExp taming revealed by #237

### LINKED ISSUE #237: cannot import @agoric/harden under SES-0.7.4 without noTameRegExp
The following CJS program:

```js
const { lockdown } = require('ses');
lockdown( { noTameError: true });
require('@agoric/harden'); // fails
```

when run in an initially-empty directory where I've done `yarn add esm ses@0.7.4 @agoric/harden@0.0.4`, yields the following error:

```
$ node -r esm t.js
/tmp/t6/node_modules/@agoric/harden/dist/harden.cjs.js:1
TypeError: RegExp.prototype.source getter called on non-RegExp object
    at Object.get source [as source] (<anonymous>)
    at Object.toString (<anonymous>)
    at /tmp/t6/node_modules/@agoric/harden/dist/harden.cjs.js:280:47
    at Array.forEach (<anonymous>)
    at getAnonIntrinsics (/tmp/t6/node_modules/@agoric/harden/dist/harden.cjs.js:266:20)
    at buildTable (/tmp/t6/node_modules/@agoric/harden/dist/harden.cjs.js:1410:22)
    at Object.<anonymous> (/tmp/t6/node_modules/@agoric/harden/dist/harden.cjs.js:1430:22)
    at Object.<anonymous> (/tmp/t6/node_modules/@agoric/harden/dist/harden.cjs.js:1)
```

The line in question (`harden.cjs.js` line 280) is trying to `toString` an undeniable:

```js

  const undeniableTuples = [
    ['Object.prototype', Object.prototype, {}],
    ['Function.prototype', Function.prototype, function foo() {}],
    ['Array.prototype', Array.prototype, []],
    ['RegExp.prototype', RegExp.prototype, /x/],
    ['Boolean.prototype', Boolean.prototype, true],
    ['Number.prototype', Number.prototype, 1],
    ['String.prototype', String.prototype, 'x'],
    ['%Generator%', Generator, aStrictGenerator],
    ['%AsyncGenerator%', AsyncGenerator, aStrictAsyncGenerator],
    ['%AsyncFunction%', AsyncFunctionPrototype, aStrictAsyncFunction],
  ];

  undeniableTuples.forEach(tuple => {
    const name = tuple[0];
    const undeniable = tuple[1];
    let start = tuple[2];
    if (start === undefined) {
      return;
    }
    start = Object(start);
    if (undeniable === start) {
      return;
    }
    if (undeniable === getProto(start)) {
      return;
    }
    throw new Error(`Unexpected undeniable: ${undeniable}`);
  });
```

If I change the `${undeniable}` to `${name}`, it reveals the unexpected undeniable:

```
Error: Unexpected undeniable: RegExp.prototype
```

I'm guessing that our fix for #230 was incomplete somehow, and the check that `harden` does is confused. There are two problems here: the first triggering this Error, and the second is that the undeniable in question throws a second error when the first one tries to call `toString` on `RegExp.prototype`.

### PR DESCRIPTION
**Pull request by erights**
Fixes #237 

The constructor and prototype structure of the regexp taming was wrong in many ways, including leakage of the `unsafeRegExp` constructor, which is a security hole. I first wrote the new test cases in this PR to demonstrate six cases that fail to work with the old structure. All those cases pass now.

On the way, I discovered https://github.com/Agoric/SES-shim/issues/239 which I'll fix in a separate PR

### CODE REVIEW

**Comment by erights** [comment]
I am getting 3 test262 failures. Not a merge candidate until fixed.

**Comment by erights** [comment]
I am now excluding those three new failures because they are similar to two existing failures that need to be diagnosed together. See https://github.com/Agoric/SES-shim/issues/242

**Comment by erights** [comment]
This PR is again a candidate.

**Comment by warner** [comment]
please rebase and/or squash this before landing, there's some internal merging in this branch that doesn't need to be in our final history

**Comment by erights** [comment]
Closing this in favor of new PR with the same code

**Pull request closed without merging**
